import os
base = "C:\\Users\\Dell\\Documents\\Codex\\2026-07-08\\listing-listing-1-75-125-2"

def write_file(path, lines):
    with open(path, "w", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")
    print("Fixed: " + path)

# AdvancedSettings.tsx
write_file(os.path.join(base, "components", "AdvancedSettings.tsx"), [
    '"use client";',
    "",
    'import { AdvancedSettings, WritingStyle } from "@/types";',
    'import { Settings2 } from "lucide-react";',
    'import { useState } from "react";',
    "",
    "interface AdvancedSettingsProps {",
    "  settings: AdvancedSettings;",
    "  onChange: (settings: AdvancedSettings) => void;",
    "}",
    "",
    "export default function AdvancedSettingsPanel({ settings, onChange }: AdvancedSettingsProps) {",
    "  const [open, setOpen] = useState(false);",
    "",
    "  const update = (partial: Partial<AdvancedSettings>) => {",
    "    onChange({ ...settings, ...partial });",
    "  };",
    "",
    "  return (",
    "    <div>",
    '      <button',
    '        className="flex items-center gap-1.5 text-sm font-medium transition-colors"',
    '        style={{ color: "var(--text-secondary)" }}',
    "        onClick={() => setOpen(!open)}",
    "      >",
    "        <Settings2 size={16} />",
    "        Advanced Settings",
    '        <span className="ml-1">{open ? "\\u25b2" : "\\u25bc"}</span>',
    "      </button>",
    "",
    "      {open && (",
    '        <div className="mt-3 p-4 rounded-lg border" style={{ borderColor: "var(--border)", background: "var(--bg-secondary)" }}>',
    '          <div className="grid gap-4 sm:grid-cols-2">',
    "            <div>",
    '              <label className="block text-xs font-medium mb-1" style={{ color: "var(--text-secondary)" }}>',
    "                Title Max Length: {settings.titleMaxLength}",
    "              </label>",
    "              <input",
    '                type="range"',
    "                min={50}",
    "                max={200}",
    "                value={settings.titleMaxLength}",
    "                onChange={(e) => update({ titleMaxLength: parseInt(e.target.value) })}",
    '                className="w-full"',
    "              />",
    "            </div>",
    "",
    "            <div>",
    '              <label className="block text-xs font-medium mb-1" style={{ color: "var(--text-secondary)" }}>',
    "                Highlight Max Length: {settings.highlightMaxLength}",
    "              </label>",
    "              <input",
    '                type="range"',
    "                min={80}",
    "                max={250}",
    "                value={settings.highlightMaxLength}",
    "                onChange={(e) => update({ highlightMaxLength: parseInt(e.target.value) })}",
    '                className="w-full"',
    "              />",
    "            </div>",
    "",
    "            <div>",
    '              <label className="block text-xs font-medium mb-1" style={{ color: "var(--text-secondary)" }}>',
    "                Writing Style",
    "              </label>",
    "              <select",
    '                className="select-field"',
    "                value={settings.writingStyle}",
    "                onChange={(e) => update({ writingStyle: e.target.value as WritingStyle })}",
    "              >",
    '                <option value="seo">SEO Priority</option>',
    '                <option value="balanced">Balanced</option>',
    '                <option value="conversion">Conversion Priority</option>',
    "              </select>",
    "            </div>",
    "",
    '            <div className="flex items-start gap-4 pt-5">',
    '              <label className="flex items-center gap-2 text-sm cursor-pointer">',
    "                <input",
    "                  type=\"checkbox\"",
    "                  checked={settings.strictDedupe}",
    "                  onChange={(e) => update({ strictDedupe: e.target.checked })}",
    '                  className="rounded"',
    "                />",
    "                Strict Deduplication",
    "              </label>",
    "",
    '              <label className="flex items-center gap-2 text-sm cursor-pointer">',
    "                <input",
    "                  type=\"checkbox\"",
    "                  checked={settings.amazonCompliance}",
    "                  onChange={(e) => update({ amazonCompliance: e.target.checked })}",
    '                  className="rounded"',
    "                />",
    "                Amazon Compliance Filter",
    "              </label>",
    "            </div>",
    "          </div>",
    "        </div>",
    "      )}",
    "    </div>",
    "  );",
    "}",
    "",
])

# OutputModeSelector.tsx
write_file(os.path.join(base, "components", "OutputModeSelector.tsx"), [
    '"use client";',
    "",
    'import { OutputMode } from "@/types";',
    "",
    "interface OutputModeSelectorProps {",
    "  value: OutputMode;",
    "  onChange: (value: OutputMode) => void;",
    "}",
    "",
    "const modes: { value: OutputMode; label: string; description: string }[] = [",
    '  { value: "title-highlights", label: "Title + Highlights", description: "Title (\\u226475 chars) + Highlight (\\u2264125 chars)" },',
    '  { value: "bullets", label: "Bullet Points", description: "5 Amazon-style bullet points" },',
    '  { value: "description", label: "Product Description", description: "Full product description" },',
    '  { value: "all", label: "Generate All", description: "Title + Highlights + Bullets + Description" },',
    "];",
    "",
    "export default function OutputModeSelector({ value, onChange }: OutputModeSelectorProps) {",
    "  return (",
    "    <div>",
    '      <label className="block text-sm font-medium mb-1.5" style={{ color: "var(--text-secondary)" }}>',
    "        Output Mode",
    "      </label>",
    '      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">',
    "        {modes.map((mode) => (",
    "          <button",
    "            key={mode.value}",
    '            className="text-left p-3 rounded-lg border text-sm transition-all"',
    "            style={{",
    "              background: value === mode.value ? 'var(--accent)' : 'var(--bg-secondary)',",
    "              borderColor: value === mode.value ? 'var(--accent)' : 'var(--border)',",
    "              color: value === mode.value ? '#fff' : 'var(--text-primary)',",
    "            }}",
    "            onClick={() => onChange(mode.value)}",
    "          >",
    "            <div className=\"font-medium\">{mode.label}</div>",
    '            <div className="text-xs mt-0.5 opacity-80">{mode.description}</div>',
    "          </button>",
    "        ))}",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "",
])

# ProductInputTextarea.tsx
write_file(os.path.join(base, "components", "ProductInputTextarea.tsx"), [
    '"use client";',
    "",
    "interface ProductInputTextareaProps {",
    "  value: string;",
    "  onChange: (value: string) => void;",
    "}",
    "",
    "export default function ProductInputTextarea({ value, onChange }: ProductInputTextareaProps) {",
    "  return (",
    "    <div>",
    '      <label className="block text-sm font-medium mb-1.5" style={{ color: "var(--text-secondary)" }}>',
    "        Product Information",
    "      </label>",
    "      <textarea",
    '        className="textarea-field font-mono text-sm"',
    "        rows={10}",
    '        placeholder={"Paste your product information here. You can include:\\n\\n- Product features and specifications\\n- Dimensions, materials, and certifications\\n- Use cases and target scenarios\\n- Your own draft copy (English, Chinese, or mixed)\\n- Competitor listings as reference\\n- Any combination of raw product data\\n\\nThe system will extract key selling points and generate Amazon-ready copy."}',
    "        value={value}",
    "        onChange={(e) => onChange(e.target.value)}",
    "      />",
    "    </div>",
    "  );",
    "}",
    "",
])

print("Done fixing all files")
