import os
base = "C:\\Users\\Dell\\Documents\\Codex\\2026-07-08\\listing-listing-1-75-125-2"

def write_ts(path, lines):
    with open(path, "w", encoding="utf-8") as f:
        for line in lines:
            f.write(line + "\n")
    print("Written: " + path)

# 1. titlePrompt.ts
write_ts(os.path.join(base, "prompts", "titlePrompt.ts"), [
    'import { ProductFacts, RankedSellingPoint } from "@/types";',
    'import { styleGuideForLanguage } from "@/lib/language";',
    "",
    "export function buildTitlePrompt(",
    "  brand: string,",
    "  targetLanguage: string,",
    "  facts: ProductFacts,",
    "  rankedPoints: RankedSellingPoint[],",
    "  titleMaxLength: number,",
    "  existingHighlights?: string",
    "): string {",
    "  const factSummary = facts.features.slice(0, 6).join('; ');",
    "  const topPoints = rankedPoints.slice(0, 5).map(function(p) { return p.text; }).join('; ');",
    "",
    "  var prompt = '';",
    "  prompt += '\\n';",
    "  prompt += 'You are an expert Amazon listing copywriter.\\n';",
    "  prompt += '\\n';",
    "  prompt += 'TASK: Generate an Amazon product title.\\n';",
    "  prompt += '\\n';",
    "  prompt += 'BRAND: ' + brand + '\\n';",
    "  prompt += 'TARGET LANGUAGE: ' + targetLanguage + '\\n';",
    '  prompt += "TITLE MAX LENGTH: " + titleMaxLength + " characters (including the brand name)\\n";',
    "  prompt += '\\n';",
    "  prompt += 'STYLE GUIDE: ' + styleGuideForLanguage(targetLanguage) + '\\n';",
    "  prompt += '\\n';",
    "  prompt += 'PRODUCT FACTS:\\n';",
    "  prompt += 'Category: ' + facts.category + '\\n';",
    "  prompt += 'Key features: ' + factSummary + '\\n';",
    "  prompt += 'Capacities/specs: ' + facts.capacities.join(', ') + '\\n';",
    "  prompt += 'Materials: ' + facts.materials.join(', ') + '\\n';",
    "  prompt += 'Certifications: ' + facts.certifications.join(', ') + '\\n';",
    "  prompt += 'Use cases: ' + facts.useCases.join(', ') + '\\n';",
    "  prompt += '\\n';",
    "  prompt += 'TOP SELLING POINTS (ranked by importance):\\n';",
    "  prompt += topPoints + '\\n';",
    "  prompt += '\\n';",
    '  prompt += "HARD REQUIREMENTS:\\n";',
    '  prompt += "1. The title MUST start with the brand '" + brand + "' followed by a space.\\n";',
    '  prompt += "2. TOTAL title length MUST NOT exceed " + titleMaxLength + " characters (count the brand too).\\n";',
    '  prompt += "3. Write in natural, fluent " + targetLanguage + " with proper word order.\\n";',
    '  prompt += "4. Prefer this structure: Brand + Core product keyword + Key spec/capacity + Core feature + Differentiator.\\n";',
    '  prompt += "5. Include the most important keywords naturally - do NOT keyword-stuff.\\n";',
    '  prompt += "6. Do NOT repeat the same word more than 2 times in the title.\\n";',
    '  prompt += "7. Do NOT use forbidden phrases like \\"best\\", \\"perfect\\", \\"No.1\\", \\"top-rated\\", \\"guaranteed\\", etc.\\n";',
    '  prompt += "8. The title must read like a real Amazon product title, not a keyword list.\\n";',
    '  prompt += "9. Avoid meaningless scene word padding (e.g., \\"for kitchen\\", \\"for home\\" if not essential).\\n";',
    '  prompt += "10. Do NOT repeat the product category word unnecessarily (e.g., \\"Ice Maker Machine Ice Maker\\").\\n";',
    "  prompt += '\\n';",
    '  prompt += "OUTPUT ONLY the title text, nothing else. No quotes, no labels.\\n";',
    "",
    "  return prompt;",
    "}",
    "",
])

# 2. highlightPrompt.ts
write_ts(os.path.join(base, "prompts", "highlightPrompt.ts"), [
    'import { ProductFacts, RankedSellingPoint } from "@/types";',
    'import { styleGuideForLanguage } from "@/lib/language";',
    "",
    "export function buildHighlightPrompt(",
    "  brand: string,",
    "  targetLanguage: string,",
    "  facts: ProductFacts,",
    "  rankedPoints: RankedSellingPoint[],",
    "  highlightMaxLength: number,",
    "  existingTitle: string",
    "): string {",
    "  const factSummary = facts.features.slice(0, 6).join('; ');",
    "  const topPoints = rankedPoints.slice(0, 5).map(function(p) { return p.text; }).join('; ');",
    "",
    "  var prompt = '';",
    "  prompt += '\\n';",
    "  prompt += 'You are an expert Amazon listing copywriter.\\n';",
    "  prompt += '\\n';",
    "  prompt += 'TASK: Generate an Amazon product highlight/short description.\\n';",
    "  prompt += '\\n';",
    "  prompt += 'TARGET LANGUAGE: ' + targetLanguage + '\\n';",
    '  prompt += "HIGHLIGHT MAX LENGTH: " + highlightMaxLength + " characters\\n";',
    "  prompt += '\\n';",
    "  prompt += 'STYLE GUIDE: ' + styleGuideForLanguage(targetLanguage) + '\\n';",
    "  prompt += '\\n';",
    "  prompt += 'PRODUCT FACTS:\\n';",
    "  prompt += 'Category: ' + facts.category + '\\n';",
    "  prompt += 'Key features: ' + factSummary + '\\n';",
    "  prompt += 'Capacities/specs: ' + facts.capacities.join(', ') + '\\n';",
    "  prompt += 'Materials: ' + facts.materials.join(', ') + '\\n';",
    "  prompt += '\\n';",
    "  prompt += 'TOP SELLING POINTS (ranked by importance):\\n';",
    "  prompt += topPoints + '\\n';",
    "  prompt += '\\n';",
    '  prompt += "EXISTING TITLE (DO NOT simply rephrase or repeat this):\\n";',
    '  prompt += '"' + existingTitle + '"\\n";',
    "  prompt += '\\n';",
    '  prompt += "HARD REQUIREMENTS:\\n";',
    '  prompt += "1. Total length MUST NOT exceed " + highlightMaxLength + " characters.\\n";',
    '  prompt += "2. Write ONE concise highlight sentence in natural " + targetLanguage + ".\\n";',
    '  prompt += "3. Do NOT simply rephrase or restate the title.\\n";',
    '  prompt += "4. Focus on selling points NOT already covered in the title.\\n";',
    '  prompt += "5. If the title already mentions core specs, write about DIFFERENT features.\\n";',
    '  prompt += "6. The same word should not appear more than 2 times across title + highlight combined.\\n";',
    '  prompt += "7. Use different vocabulary from the title where possible.\\n";',
    '  prompt += "8. Do NOT use forbidden phrases like \\"best\\", \\"perfect\\", \\"No.1\\", \\"top-rated\\", etc.\\n";',
    '  prompt += "9. The highlight should complement the title, not compete with it.\\n";',
    "  prompt += '\\n';",
    '  prompt += "OUTPUT ONLY the highlight text, nothing else. No quotes, no labels.\\n";',
    "",
    "  return prompt;",
    "}",
    "",
])

# 3. bulletsPrompt.ts
write_ts(os.path.join(base, "prompts", "bulletsPrompt.ts"), [
    'import { ProductFacts, RankedSellingPoint } from "@/types";',
    'import { styleGuideForLanguage } from "@/lib/language";',
    "",
    "export function buildBulletsPrompt(",
    "  brand: string,",
    "  targetLanguage: string,",
    "  facts: ProductFacts,",
    "  rankedPoints: RankedSellingPoint[],",
    "  existingTitle?: string",
    "): string {",
    "  const factSummary = facts.features.slice(0, 10).join('; ');",
    "  const topPoints = rankedPoints.slice(0, 8).map(function(p) { return p.text; }).join('; ');",
    "",
    "  var prompt = '';",
    "  prompt += '\\n';",
    "  prompt += 'You are an expert Amazon listing copywriter.\\n';",
    "  prompt += '\\n';",
    "  prompt += 'TASK: Generate 5 Amazon bullet points (key features).\\n';",
    "  prompt += '\\n';",
    "  prompt += 'TARGET LANGUAGE: ' + targetLanguage + '\\n';",
    "  prompt += 'STYLE GUIDE: ' + styleGuideForLanguage(targetLanguage) + '\\n';",
    "  prompt += '\\n';",
    "  prompt += 'PRODUCT FACTS:\\n';",
    "  prompt += 'Category: ' + facts.category + '\\n';",
    "  prompt += 'Key features: ' + factSummary + '\\n';",
    "  prompt += 'Capacities/specs: ' + facts.capacities.join(', ') + '\\n';",
    "  prompt += 'Materials: ' + facts.materials.join(', ') + '\\n';",
    "  prompt += 'Certifications: ' + facts.certifications.join(', ') + '\\n';",
    "  prompt += 'Accessories: ' + facts.accessories.join(', ') + '\\n';",
    "  prompt += 'Use cases: ' + facts.useCases.join(', ') + '\\n';",
    "  prompt += '\\n';",
    "  prompt += 'TOP SELLING POINTS:\\n';",
    "  prompt += topPoints + '\\n';",
    "  prompt += '\\n';",
    "  if (existingTitle) {",
    "    prompt += 'EXISTING TITLE (for reference, avoid repeating its content directly): ' + existingTitle + '\\n';",
    "  }",
    "  prompt += '\\n';",
    '  prompt += "STRUCTURE REQUIREMENTS:\\n";',
    '  prompt += "Each bullet should have:\\n";',
    '  prompt += "- A short CAPITALIZED/emphasized opener (2-4 words)\\n";',
    '  prompt += "- Then the benefit explanation + supporting details\\n";',
    "  prompt += '\\n';",
    '  prompt += "COVERAGE (cover different angles):\\n";',
    '  prompt += "1. Core performance / capacity / output\\n";',
    '  prompt += "2. Function experience / usage effect / key feature\\n";',
    '  prompt += "3. Design / portability / convenience of use\\n";',
    '  prompt += "4. Cleaning / smart control / maintenance\\n";',
    '  prompt += "5. Quietness / materials / certifications / warranty / peace of mind\\n";',
    "  prompt += '\\n';",
    '  prompt += "HARD REQUIREMENTS:\\n";',
    '  prompt += "1. Output exactly 5 bullet points, one per line.\\n";',
    '  prompt += "2. Each bullet should focus on a DIFFERENT selling point.\\n";',
    '  prompt += "3. Lead with customer benefit, then support with specs/parameters.\\n";',
    '  prompt += "4. Write in natural " + targetLanguage + ".\\n";',
    '  prompt += "5. Do NOT keyword-stuff.\\n";',
    '  prompt += "6. Do NOT use forbidden phrases like \\"best\\", \\"perfect\\", \\"No.1\\", \\"top-rated\\", etc.\\n";',
    '  prompt += "7. Do NOT make exaggerated or unsubstantiated claims.\\n";',
    '  prompt += "8. Do NOT repeat what\\'s already heavily covered in the title.\\n";',
    '  prompt += "9. Each bullet should sound like a real Amazon listing bullet point.\\n";',
    "  prompt += '\\n';",
    '  prompt += "OUTPUT 5 lines, each line is one bullet point. No numbers, no bullet symbols.\\n";',
    "",
    "  return prompt;",
    "}",
    "",
])

# 4. descriptionPrompt.ts
write_ts(os.path.join(base, "prompts", "descriptionPrompt.ts"), [
    'import { ProductFacts, RankedSellingPoint } from "@/types";',
    'import { styleGuideForLanguage } from "@/lib/language";',
    "",
    "export function buildDescriptionPrompt(",
    "  brand: string,",
    "  targetLanguage: string,",
    "  facts: ProductFacts,",
    "  rankedPoints: RankedSellingPoint[],",
    "  existingBullets?: string[]",
    "): string {",
    "  const factSummary = facts.features.slice(0, 10).join('; ');",
    "  const topPoints = rankedPoints.slice(0, 6).map(function(p) { return p.text; }).join('; ');",
    "",
    "  var prompt = '';",
    "  prompt += '\\n';",
    "  prompt += 'You are an expert Amazon listing copywriter.\\n';",
    "  prompt += '\\n';",
    "  prompt += 'TASK: Generate a product description for an Amazon listing.\\n';",
    "  prompt += '\\n';",
    "  prompt += 'TARGET LANGUAGE: ' + targetLanguage + '\\n';",
    "  prompt += 'STYLE GUIDE: ' + styleGuideForLanguage(targetLanguage) + '\\n';",
    "  prompt += '\\n';",
    "  prompt += 'PRODUCT FACTS:\\n';",
    "  prompt += 'Brand: ' + brand + '\\n';",
    "  prompt += 'Category: ' + facts.category + '\\n';",
    "  prompt += 'Key features: ' + factSummary + '\\n';",
    "  prompt += 'Capacities/specs: ' + facts.capacities.join(', ') + '\\n';",
    "  prompt += 'Dimensions: ' + facts.dimensions.join(', ') + '\\n';",
    "  prompt += 'Materials: ' + facts.materials.join(', ') + '\\n';",
    "  prompt += 'Certifications: ' + facts.certifications.join(', ') + '\\n';",
    "  prompt += 'Accessories: ' + facts.accessories.join(', ') + '\\n';",
    "  prompt += 'Use cases: ' + facts.useCases.join(', ') + '\\n';",
    "  prompt += 'Support/Warranty: ' + facts.supportInfo.join(', ') + '\\n';",
    "  prompt += '\\n';",
    "  prompt += 'TOP SELLING POINTS:\\n';",
    "  prompt += topPoints + '\\n';",
    "  prompt += '\\n';",
    "  if (existingBullets) {",
    "    prompt += 'EXISTING BULLET POINTS (for reference, avoid simply repeating them): ' + existingBullets.join(' | ') + '\\n';",
    "  }",
    "  prompt += '\\n';",
    '  prompt += "RECOMMENDED STRUCTURE (3-5 paragraphs):\\n";',
    '  prompt += "1. Overall product value / core use case / scenario\\n";',
    '  prompt += "2. Key specifications + daily use benefits\\n";',
    '  prompt += "3. Convenience features (cleaning, control, portability, etc.)\\n";',
    '  prompt += "4. Trust information (quietness, materials, certifications, warranty, after-sales)\\n";',
    "  prompt += '\\n';",
    '  prompt += "HARD REQUIREMENTS:\\n";',
    '  prompt += "1. Write a complete, flowing product description in natural " + targetLanguage + ".\\n";',
    '  prompt += "2. Do NOT keyword-stuff.\\n";',
    '  prompt += "3. Do NOT just repeat bullet points verbatim.\\n";',
    '  prompt += "4. Do NOT use forbidden phrases like \\"best\\", \\"perfect\\", \\"No.1\\", \\"top-rated\\", etc.\\n";',
    '  prompt += "5. Write in a persuasive but honest tone - good conversion without exaggeration.\\n";',
    '  prompt += "6. The description should feel cohesive and well-structured.\\n";',
    '  prompt += "7. Include relevant specifics (specs, features, benefits) naturally within the narrative.\\n";',
    '  prompt += "8. Follow the language style guide for " + targetLanguage + ".\\n";',
    "  prompt += '\\n';",
    '  prompt += "OUTPUT ONLY the description text. Use proper paragraph breaks.\\n";',
    "",
    "  return prompt;",
    "}",
    "",
])

print("All prompt files rewritten successfully")
